In [ ]:
import requests
import pandas as pd

In [ ]:
api_base_url = 'https://anapioficeandfire.com/api'

In [ ]:
books_list = requests.get(
    f'{api_base_url}/books'
).json()

In [ ]:
len(books_list)

10

In [ ]:
df_books = pd.DataFrame(books_list)
df_books.head()

,url,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,https://anapioficeandfire.com/api/books/1,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
1,https://anapioficeandfire.com/api/books/2,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
2,https://anapioficeandfire.com/api/books/3,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
3,https://anapioficeandfire.com/api/books/4,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
4,https://anapioficeandfire.com/api/books/5,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...

In [ ]:
houses_list = requests.get(
    f'{api_base_url}/houses'
).json()

In [ ]:
len(houses_list)

10

In [ ]:
df_houses = pd.DataFrame(houses_list)
df_houses.head()

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,[],[],,,https://anapioficeandfire.com/api/houses/229,,,,[],[],[]
1,https://anapioficeandfire.com/api/houses/2,House Allyrion of Godsgrace,Dorne,"Gyronny Gules and Sable, a hand couped Or",No Foe May Pass,[],[Godsgrace],https://anapioficeandfire.com/api/characters/298,https://anapioficeandfire.com/api/characters/1922,https://anapioficeandfire.com/api/houses/285,,,,[],[],[https://anapioficeandfire.com/api/characters/...
2,https://anapioficeandfire.com/api/houses/3,House Amber,The North,,,[],[],,,,,,,[],[],[]
3,https://anapioficeandfire.com/api/houses/4,House Ambrose,The Reach,"Or, semy of ants gules",Never Resting,[],[],https://anapioficeandfire.com/api/characters/141,,https://anapioficeandfire.com/api/houses/398,,,,[],[],[https://anapioficeandfire.com/api/characters/...
4,https://anapioficeandfire.com/api/houses/5,House Appleton of Appleton,The Reach,"Or, an apple tree eradicated proper fructed gu...",,[],[Appleton],,,https://anapioficeandfire.com/api/houses/398,,,,[],[],[]

In [ ]:
houses_with_Titles = requests.get(
    f'{api_base_url}/houses',
    params={'hasTitles': 'true'}
).json()

In [ ]:
len(houses_with_Titles)

10

In [ ]:
df_houses_with_Titles = pd.DataFrame(houses_with_Titles)
df_houses_with_Titles.head()

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://anapioficeandfire.com/api/houses/7,House Arryn of the Eyrie,The Vale,A sky-blue falcon soaring against a white moon...,As High as Honor,"[King of Mountain and Vale (formerly), Lord of...","[The Eyrie (summer), Gates of the Moon (winter)]",https://anapioficeandfire.com/api/characters/894,https://anapioficeandfire.com/api/characters/477,https://anapioficeandfire.com/api/houses/16,Coming of the Andals,https://anapioficeandfire.com/api/characters/144,,[],[https://anapioficeandfire.com/api/houses/6],[https://anapioficeandfire.com/api/characters/...
1,https://anapioficeandfire.com/api/houses/8,House Ashford of Ashford,The Reach,"Tenny, a sun in splendour beneath a chevron in...",Our Sun Shines Bright,[Lord of Ashford],[Ashford],,,https://anapioficeandfire.com/api/houses/398,,,,[],[],[https://anapioficeandfire.com/api/characters/...
2,https://anapioficeandfire.com/api/houses/10,House Baelish of Harrenhal,The Riverlands,"A field of silver mockingbirds, on a green fie...",,"[Lord Paramount of the Trident, Lord of Harren...",[Harrenhal],https://anapioficeandfire.com/api/characters/823,,https://anapioficeandfire.com/api/houses/16,299 AC,https://anapioficeandfire.com/api/characters/823,,[],[],[https://anapioficeandfire.com/api/characters/...
3,https://anapioficeandfire.com/api/houses/13,House Banefort of Banefort,The Westerlands,"A black hooded man, on a grey field, within a ...",,[Lord of Banefort],[Banefort],https://anapioficeandfire.com/api/characters/837,,https://anapioficeandfire.com/api/houses/229,,https://anapioficeandfire.com/api/characters/497,,[],[],[https://anapioficeandfire.com/api/characters/...
4,https://anapioficeandfire.com/api/houses/14,House Bar Emmon of Sharp Point,The Crownlands,"Fretty argent and white, a swordfish embowed h...",,[Lord of Sharp Point],[Sharp Point],https://anapioficeandfire.com/api/characters/332,,https://anapioficeandfire.com/api/houses/15,,,,[],[],[https://anapioficeandfire.com/api/characters/...