In [6]:
import polars as pl
df_pl = pl.read_csv("train.csv")

In [26]:
df_pl.describe()

shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64       ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0     ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208 ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693429 ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0       ┆ A10   ┆ C        │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925     ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542   ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0      ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.3292  ┆ T     ┆ S        │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────┴──────────┘

In [27]:
df_pl.dtypes

[Int64,
 Int64,
 Int64,
 String,
 String,
 Float64,
 Int64,
 Int64,
 String,
 Float64,
 String,
 String]

In [14]:
df_pl.null_count()

shape: (1, 12)
┌─────────────┬──────────┬────────┬──────┬───┬────────┬──────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name ┆ … ┆ Ticket ┆ Fare ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---  ┆   ┆ ---    ┆ ---  ┆ ---   ┆ ---      │
│ u32         ┆ u32      ┆ u32    ┆ u32  ┆   ┆ u32    ┆ u32  ┆ u32   ┆ u32      │
╞═════════════╪══════════╪════════╪══════╪═══╪════════╪══════╪═══════╪══════════╡
│ 0           ┆ 0        ┆ 0      ┆ 0    ┆ … ┆ 0      ┆ 0    ┆ 687   ┆ 2        │
└─────────────┴──────────┴────────┴──────┴───┴────────┴──────┴───────┴──────────┘

In [28]:
df_pl.select(pl.all().exclude(pl.String)).mean()

shape: (1, 7)
┌─────────────┬──────────┬──────────┬───────────┬──────────┬──────────┬───────────┐
│ PassengerId ┆ Survived ┆ Pclass   ┆ Age       ┆ SibSp    ┆ Parch    ┆ Fare      │
│ ---         ┆ ---      ┆ ---      ┆ ---       ┆ ---      ┆ ---      ┆ ---       │
│ f64         ┆ f64      ┆ f64      ┆ f64       ┆ f64      ┆ f64      ┆ f64       │
╞═════════════╪══════════╪══════════╪═══════════╪══════════╪══════════╪═══════════╡
│ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ 29.699118 ┆ 0.523008 ┆ 0.381594 ┆ 32.204208 │
└─────────────┴──────────┴──────────┴───────────┴──────────┴──────────┴───────────┘

In [25]:
df_pl.get_column("Pclass").value_counts()

shape: (3, 2)
┌────────┬───────┐
│ Pclass ┆ count │
│ ---    ┆ ---   │
│ i64    ┆ u32   │
╞════════╪═══════╡
│ 3      ┆ 491   │
│ 2      ┆ 184   │
│ 1      ┆ 216   │
└────────┴───────┘

In [17]:
df_pl.group_by("Sex").agg(pl.col("Survived").sum())

shape: (2, 2)
┌────────┬──────────┐
│ Sex    ┆ Survived │
│ ---    ┆ ---      │
│ str    ┆ i64      │
╞════════╪══════════╡
│ female ┆ 233      │
│ male   ┆ 109      │
└────────┴──────────┘

In [20]:
df_pl.filter(pl.col('Age') > 44).head(10)

shape: (10, 12)
┌─────────────┬──────────┬────────┬─────────────────┬───┬─────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name            ┆ … ┆ Ticket      ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---             ┆   ┆ ---         ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str             ┆   ┆ str         ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═════════════════╪═══╪═════════════╪═════════╪═══════╪══════════╡
│ 7           ┆ 0        ┆ 1      ┆ McCarthy, Mr.   ┆ … ┆ 17463       ┆ 51.8625 ┆ E46   ┆ S        │
│             ┆          ┆        ┆ Timothy J       ┆   ┆             ┆         ┆       ┆          │
│ 12          ┆ 1        ┆ 1      ┆ Bonnell, Miss.  ┆ … ┆ 113783      ┆ 26.55   ┆ C103  ┆ S        │
│             ┆          ┆        ┆ Elizabeth       ┆   ┆             ┆         ┆       ┆          │
│ 16          ┆ 1        ┆ 2      ┆ Hewlett, Mrs.   ┆ … ┆ 248706      ┆ 16.0    ┆ null  ┆ S        │
│             ┆          ┆        ┆ (Mary D         ┆   ┆             ┆         ┆       ┆          │
│             ┆          ┆        ┆ Kingcome…       ┆   ┆             ┆         ┆       ┆          │
│ 34          ┆ 0        ┆ 2      ┆ Wheadon, Mr.    ┆ … ┆ C.A. 24579  ┆ 10.5    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Edward H        ┆   ┆             ┆         ┆       ┆          │
│ 53          ┆ 1        ┆ 1      ┆ Harper, Mrs.    ┆ … ┆ PC 17572    ┆ 76.7292 ┆ D33   ┆ C        │
│             ┆          ┆        ┆ Henry Sleeper   ┆   ┆             ┆         ┆       ┆          │
│             ┆          ┆        ┆ (My…            ┆   ┆             ┆         ┆       ┆          │
│ 55          ┆ 0        ┆ 1      ┆ Ostby, Mr.      ┆ … ┆ 113509      ┆ 61.9792 ┆ B30   ┆ C        │
│             ┆          ┆        ┆ Engelhart       ┆   ┆             ┆         ┆       ┆          │
│             ┆          ┆        ┆ Cornelius       ┆   ┆             ┆         ┆       ┆          │
│ 63          ┆ 0        ┆ 1      ┆ Harris, Mr.     ┆ … ┆ 36973       ┆ 83.475  ┆ C83   ┆ S        │
│             ┆          ┆        ┆ Henry Birkhardt ┆   ┆             ┆         ┆       ┆          │
│ 93          ┆ 0        ┆ 1      ┆ Chaffee, Mr.    ┆ … ┆ W.E.P. 5734 ┆ 61.175  ┆ E31   ┆ S        │
│             ┆          ┆        ┆ Herbert Fuller  ┆   ┆             ┆         ┆       ┆          │
│ 95          ┆ 0        ┆ 3      ┆ Coxon, Mr.      ┆ … ┆ 364500      ┆ 7.25    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Daniel          ┆   ┆             ┆         ┆       ┆          │
│ 97          ┆ 0        ┆ 1      ┆ Goldschmidt,    ┆ … ┆ PC 17754    ┆ 34.6542 ┆ A5    ┆ C        │
│             ┆          ┆        ┆ Mr. George B    ┆   ┆             ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴─────────────────┴───┴─────────────┴─────────┴───────┴──────────┘